services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: testapp_mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: testapp
            MYSQL_USER: testuser
            MYSQL_PASSWORD: testpass
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
